<?php

namespace RtecaBundle\Repository;

/**
 * BibliotecaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliotecaRepository extends \Doctrine\ORM\EntityRepository
{
}
